apiVersion: v1
entries:
  microcks:
  - apiVersion: v2
    appVersion: 1.5.1
    created: "2022-04-25T20:05:00.518272+02:00"
    description: Microcks Lab - API Mocking and Testing
    keywords:
    - mocks
    - microservice
    - api
    - test
    kubeVersion: '>=1.17.0-0'
    maintainers:
    - email: laurent.broudoux@gmail.com
      name: Laurent Broudoux
    name: microcks
    sources:
    - http://github.com/carolgschwend/microcks/
    type: application
    version: 1.5.1
generated: "2022-04-25T20:05:00.518272+02:00"
